global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - /etc/prometheus/rules/*.yml

scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets:
          - '10.10.10.10:9100'   # infra-server
          - '10.10.10.20:9100'   # deploy-test
          - '10.10.10.21:9100'   # staging
          - '10.10.10.14:9100'   # dev-yj99son
          - '10.10.10.11:9100'   # dev-j2hoon10
          - '10.10.10.13:9100'   # dev-ryejinn
          - '10.10.10.12:9100'   # dev-jjjh02
          - '10.10.10.15:9100'   # dev-hj
        labels:
          env: 'lxd'

  # FastAPI 백엔드 API 메트릭
  - job_name: 'fastapi'
    metrics_path: '/metrics'
    static_configs:
      - targets:
          - '10.10.10.20:8082'   # deploy-test
        labels:
          service: 'backend-api'

  - job_name: 'cadvisor'
    static_configs:
      - targets:
          - '10.10.10.10:8080'   # infra-server
          - '10.10.10.20:8080'   # deploy-test
