apiVersion: 1
policies:
  - orgId: 1
    receiver: discord-webhook
    group_by:
      - alertname
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 4h
    routes:
      - receiver: discord-webhook
        matchers:
          - severity=critical
        group_wait: 10s
        repeat_interval: 1h
      - receiver: default-email
        matchers:
          - severity=warning
        repeat_interval: 12h
